document.write("<div>");
		document.write("<table>");
			document.write("<caption>Kebab butikk i Oslo!</caption>");
			document.write("<tr>");
				document.write("<th>Bydel</th>");
				document.write("<th>Pris</th>");
				document.write("<th>god?</th>");
				document.write("<th>hva</th>");
				document.write("<th>...</th>");
				document.write("<th>Good </th>");
			document.write("</tr>");

			document.write("<tr>");
			document.write("	<td>Oslo</td>");
				document.write("<td>20Krone</td>");
				document.write("<td>-10</td>");
				document.write("<td>20 November 2019</td>");
				document.write("<td>winter</td>");
				document.write("<td>not so good</td>");
			document.write("</tr>");
			
			document.write("<tr>");
				document.write("<td>Tokoy</td>");
				document.write("<td>20Krone</td>");
				document.write("<td>10</td>");
				document.write("<td>20 November 2012</td>");
				document.write("<td>winter</td>");
				document.write("<td>good food</td>");
			document.write("</tr>");
		document.write("</table>");
document.write("</div>");